import { useState, useMemo } from "react";
import rules from "./guardrail_rules.json";

// The guardrail-admin surface — CLAUDE.md's second, deliberately different
// visual identity: calmer, more information-dense, for a sighted operator
// reviewing or editing rules, not glancing under time pressure.
//
// Rules come from guardrail_rules.json, generated by
// export_guardrail_rules.py straight out of guardrails.py's own
// CONFIRM_PATTERNS/BLOCK_PATTERNS — never a hand-copied list that can drift.
// Re-run that script after editing guardrails.py; this page always shows
// whatever it last produced.

const GROUPS = {
  send: "Communication", submit: "Communication", post: "Communication", publish: "Communication", "reply all": "Communication",
  pay: "Money", buy: "Money", purchase: "Money", checkout: "Money", transfer: "Money", donate: "Money",
  order: "Money", book: "Money", withdraw: "Money",
  // "call" deliberately left ungrouped (shows under "Other") — genuinely
  // ambiguous (a phone call vs. a financial "call" action), added from
  // competitive research (COMPETITIVE_RESEARCH.md) without forcing a
  // categorization that doesn't cleanly fit.
  "delet*": "Deletion", "remov*": "Deletion", "empty trash": "Deletion", "eras*": "Deletion", unsubscribe: "Deletion",
  "change password": "Account & security", "delete account": "Account & security", "sign out": "Account & security", revoke: "Account & security", disable: "Account & security",
  "factory reset": "Device wipe", reformat: "Device wipe", "wipe device": "Device wipe", "uninstall windows": "Device wipe",
  "disable firewall": "Security controls", "disable antivirus": "Security controls",
};

function groupOf(phrase) {
  return GROUPS[phrase] || "Other";
}

// Reimplements guardrails.check()'s exact logic client-side, for the live
// tester below: block patterns win, then confirm patterns, else allow.
// Same haystack shape (`name control_type automation_id`), same
// case-insensitive regex search.
function checkClientSide(name, controlType, automationId) {
  const haystack = `${name} ${controlType} ${automationId}`.toLowerCase();
  const test = (r) => haystack.match(new RegExp(r.pattern, "i"));
  const blockHit = rules.block.find(test);
  if (blockHit) return { tier: "block", rule: blockHit };
  const confirmHit = rules.confirm.find(test);
  if (confirmHit) return { tier: "confirm", rule: confirmHit };
  return { tier: "allow", rule: null };
}

function groupRules(list) {
  const byGroup = {};
  for (const r of list) {
    const g = groupOf(r.phrase);
    (byGroup[g] ||= []).push(r);
  }
  return byGroup;
}

function RuleChip({ rule, tone }) {
  return (
    <div style={{ ...css.chip, ...(tone === "block" ? css.chipBlock : css.chipConfirm) }}>
      <span style={css.chipPattern}>{rule.pattern}</span>
      <span style={css.chipPhrase}>“{rule.phrase}”</span>
    </div>
  );
}

function Section({ title, subtitle, tone, list, filter }) {
  const filtered = filter ? list.filter((r) => r.phrase.includes(filter)) : list;
  const grouped = groupRules(filtered);
  const groupNames = Object.keys(grouped);
  return (
    <section style={css.section}>
      <div style={{ ...css.sectionHeader, borderColor: tone === "block" ? "var(--block)" : "var(--confirm)" }}>
        <h2 style={css.sectionTitle}>{title}</h2>
        <span style={css.sectionCount}>{filtered.length} pattern{filtered.length === 1 ? "" : "s"}</span>
      </div>
      <p style={css.sectionSubtitle}>{subtitle}</p>
      {groupNames.length === 0 && <p style={css.emptyNote}>No patterns match “{filter}”.</p>}
      {groupNames.map((g) => (
        <div key={g} style={css.group}>
          <h3 style={css.groupTitle}>{g}</h3>
          <div style={css.chipRow}>
            {grouped[g].map((r) => <RuleChip key={r.pattern} rule={r} tone={tone} />)}
          </div>
        </div>
      ))}
    </section>
  );
}

export default function RelayAdminUI() {
  const [filter, setFilter] = useState("");
  const [name, setName] = useState("Send");
  const [controlType, setControlType] = useState("Button");
  const [automationId, setAutomationId] = useState("");
  const result = useMemo(() => checkClientSide(name, controlType, automationId), [name, controlType, automationId]);

  return (
    <div style={css.app}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Public+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@500;600&display=swap');
        .relay-admin :focus-visible { outline: 3px solid var(--focus); outline-offset: 2px; }
        .relay-admin input:focus-visible { outline-offset: 0; }
      `}</style>

      <div className="relay-admin">
        <header style={css.header}>
          <p style={css.kicker}>Relay — setup surface</p>
          <h1 style={css.h1}>Guardrail rules</h1>
          <p style={css.headerNote}>
            Generated from <code style={css.inlineCode}>guardrails.py</code>'s real
            <code style={css.inlineCode}>CONFIRM_PATTERNS</code> and
            <code style={css.inlineCode}>BLOCK_PATTERNS</code> lists — {rules.confirm.length} confirm
            patterns, {rules.block.length} block patterns, as of the last run of{" "}
            <code style={css.inlineCode}>export_guardrail_rules.py</code>. This page only reads that
            export; it does not write back to the source file. That's deliberate — CLAUDE.md is explicit
            that these rules should get harder to change, not easier. To add or remove a rule, edit
            <code style={css.inlineCode}>guardrails.py</code> directly and re-run the export.
          </p>
        </header>

        <div style={css.searchRow}>
          <label htmlFor="filter" style={css.searchLabel}>Filter patterns</label>
          <input
            id="filter"
            style={css.searchInput}
            type="text"
            placeholder="e.g. delete, password, firewall"
            value={filter}
            onChange={(e) => setFilter(e.target.value.toLowerCase())}
          />
        </div>

        <Section
          title="Confirm"
          tone="confirm"
          subtitle='A control whose name, control type, or automation id matches one of these phrases needs a spoken "yes" before Relay executes it.'
          list={rules.confirm}
          filter={filter}
        />
        <Section
          title="Block"
          tone="block"
          subtitle="A control matching one of these phrases never executes, regardless of confirmation. This list is kept deliberately short."
          list={rules.block}
          filter={filter}
        />

        <section style={css.tester}>
          <h2 style={css.testerTitle}>Try a control against these rules</h2>
          <p style={css.sectionSubtitle}>
            Runs the same matching guardrails.check() does — block patterns first, then confirm, otherwise allow.
          </p>
          <div style={css.testerGrid}>
            <label style={css.testerField}>
              <span style={css.testerLabel}>Name</span>
              <input style={css.testerInput} value={name} onChange={(e) => setName(e.target.value)} />
            </label>
            <label style={css.testerField}>
              <span style={css.testerLabel}>Control type</span>
              <input style={css.testerInput} value={controlType} onChange={(e) => setControlType(e.target.value)} />
            </label>
            <label style={css.testerField}>
              <span style={css.testerLabel}>Automation id</span>
              <input style={css.testerInput} value={automationId} onChange={(e) => setAutomationId(e.target.value)} />
            </label>
          </div>
          <div
            style={{
              ...css.result,
              ...(result.tier === "block" ? css.resultBlock : {}),
              ...(result.tier === "confirm" ? css.resultConfirm : {}),
              ...(result.tier === "allow" ? css.resultAllow : {}),
            }}
            aria-live="polite"
          >
            <strong style={css.resultTier}>{result.tier.toUpperCase()}</strong>
            <span>
              {result.tier === "allow"
                ? `"${name}" did not match any confirm or block pattern.`
                : `"${name}" matches ${result.rule.pattern} (“${result.rule.phrase}”).`}
            </span>
          </div>
        </section>
      </div>
    </div>
  );
}

const css = {
  app: {
    "--bg": "#F1F4F7",
    "--surface": "#FFFFFF",
    "--surface-2": "#E4E9EF",
    "--ink": "#131C24",
    "--ink-soft": "#47535E",
    "--line": "#D4DCE3",
    "--confirm": "#2A5C8A",
    "--confirm-text": "#1D4160",
    "--confirm-surface": "#E7EFF6",
    "--block": "#22262B",
    "--block-text": "#22262B",
    "--block-surface": "#E7E9EB",
    "--allow-text": "#274A31",
    "--allow-surface": "#E7F0E9",
    "--chip-mono-text": "#3A434C",
    "--focus": "#1D4160",
    minHeight: "100vh",
    background: "var(--bg)",
    color: "var(--ink)",
    fontFamily: "'Public Sans', system-ui, 'Segoe UI', sans-serif",
    fontSize: 18,
    lineHeight: 1.55,
    padding: "40px 28px 64px",
  },
  header: { maxWidth: 760, margin: "0 auto 28px" },
  kicker: { fontSize: 18, color: "var(--ink-soft)", margin: "0 0 6px", fontWeight: 600 },
  h1: { fontSize: 34, fontWeight: 700, margin: "0 0 14px", textWrap: "balance" },
  headerNote: { fontSize: 18, color: "var(--ink-soft)", maxWidth: "68ch", margin: 0 },
  inlineCode: {
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
    background: "var(--surface-2)",
    borderRadius: 4,
    padding: "1px 6px",
    margin: "0 3px",
    fontSize: 18,
  },
  searchRow: {
    maxWidth: 760, margin: "0 auto 32px",
    display: "flex", flexDirection: "column", gap: 8,
  },
  searchLabel: { fontSize: 18, fontWeight: 600 },
  searchInput: {
    minHeight: 48, fontSize: 18, padding: "0 16px",
    border: "1.5px solid var(--line)", borderRadius: 10,
    background: "var(--surface)", color: "var(--ink)", font: "inherit",
  },
  section: { maxWidth: 760, margin: "0 auto 32px" },
  sectionHeader: {
    display: "flex", justifyContent: "space-between", alignItems: "baseline",
    borderBottom: "3px solid var(--line)", paddingBottom: 8, marginBottom: 8,
  },
  sectionTitle: { fontSize: 22, fontWeight: 700, margin: 0 },
  sectionCount: {
    fontFamily: "'JetBrains Mono', ui-monospace, monospace", fontSize: 18, color: "var(--ink-soft)",
  },
  sectionSubtitle: { fontSize: 18, color: "var(--ink-soft)", margin: "0 0 18px", maxWidth: "68ch" },
  emptyNote: { fontSize: 18, color: "var(--ink-soft)", fontStyle: "italic" },
  group: { marginBottom: 18 },
  groupTitle: { fontSize: 18, fontWeight: 600, margin: "0 0 10px", color: "var(--ink-soft)" },
  chipRow: { display: "flex", flexWrap: "wrap", gap: 10 },
  chip: {
    display: "flex", flexDirection: "column", gap: 2,
    padding: "8px 14px", borderRadius: 10, border: "1.5px solid var(--line)",
    background: "var(--surface)",
  },
  chipConfirm: { borderColor: "var(--confirm)", background: "var(--confirm-surface)" },
  chipBlock: { borderColor: "var(--block)", background: "var(--block-surface)" },
  // --chip-mono-text, not --ink-soft: verified 2026-09-10 via a real WCAG
  // contrast check (check_contrast.mjs) — ink-soft (#47535E) on the tinted
  // chip backgrounds measured 6.78:1 / 6.47:1, both under the 7:1 AAA floor.
  chipPattern: { fontFamily: "'JetBrains Mono', ui-monospace, monospace", fontSize: 18, color: "var(--chip-mono-text)" },
  chipPhrase: { fontSize: 18, fontWeight: 600 },
  tester: {
    maxWidth: 760, margin: "40px auto 0", padding: 24,
    background: "var(--surface)", border: "1.5px solid var(--line)", borderRadius: 14,
  },
  testerTitle: { fontSize: 22, fontWeight: 700, margin: "0 0 6px" },
  testerGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14, margin: "18px 0" },
  testerField: { display: "flex", flexDirection: "column", gap: 6 },
  testerLabel: { fontSize: 18, fontWeight: 600, color: "var(--ink-soft)" },
  testerInput: {
    minHeight: 48, fontSize: 18, padding: "0 14px",
    border: "1.5px solid var(--line)", borderRadius: 10,
    background: "var(--bg)", color: "var(--ink)", font: "inherit",
  },
  result: {
    display: "flex", flexWrap: "wrap", alignItems: "baseline", gap: 10,
    padding: "14px 18px", borderRadius: 10, border: "1.5px solid var(--line)",
    fontSize: 18,
  },
  resultTier: { fontFamily: "'JetBrains Mono', ui-monospace, monospace", fontSize: 18, letterSpacing: "0.03em" },
  resultAllow: { background: "var(--allow-surface)", color: "var(--allow-text)", borderColor: "var(--allow-text)" },
  resultConfirm: { background: "var(--confirm-surface)", color: "var(--confirm-text)", borderColor: "var(--confirm)" },
  resultBlock: { background: "var(--block-surface)", color: "var(--block-text)", borderColor: "var(--block)" },
};
